### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by thekroko** [thekroko/uthgard-herald#35]
https://travis-ci.org/thekroko/uthgard-herald

Can someone take a look?

**Comment by burfo** [comment]
Yeah, I was noticing this this yesterday.  Our tests have never worked mainly because I intentionally ignored the auto-created tests when I initially created the app.

Alternatively, we could update the Travis-CI to just run a linter or something instead of the non-useful tests.

**Comment by andir** [comment]
A linter might be worth nomatter what we decide here :-)

I tried to understand the tests yesterday but that stuff just beats me.. I've no idea why that stuff is failing.

**Comment by OliverRadini** [comment]
currently it's misleading that it's breaking, I think it's pointless to check for tests that we've never really used

**Comment by andir** [comment]
Well even if the tests do not test functionality I'd love if they'd try to instantiate a class/view/component/.. so we know that the syntax is off at some part. One can easily overlook that during PR review.
But other than that I do not mind not running tests (currently).

**Comment by OliverRadini** [comment]
@andir if you want them you may need to be the one to try to add them, as no one else is so far

**Comment by thekroko** [comment]
I think having a full set of tests might be overkill, but a simple start-up tests should definitely be there and working. Would be nice to be able to say "hey, this builds, starts up, and I can make a request without everything bursting into flames".

Can someone create a very simple test that doesn't fail & pass travis CI?

**Comment by andir** [comment]
`Eist` (on IRC) was working on that. No idea if he is on github yet.

**Comment by burfo** [comment]
I can definitely clean up the tests that are there now; main problem with them failing is because they were created for an older version of angular.
