### ISSUE TITLE
you slow down multiple request now ?!?!

### ISSUE THREAD

**Issue by gilly42** [thekroko/uthgard-herald#6]
hey, i noticed that you configured your api to response to "high frequency" request with a delay of 30s-60s.

I was trying to tell you that somebody will do that. (this time i was - about 14 request per min) to build my database with the uthgard data.

Good for you that you have now a way to block this kind of "get-all-data", but i saw it is only ip based, hopefully it is not ip4 only .... every normal internet connection with ipv6 hat 32k ipv6 addresses ;) or even a tor proxy would bypass the limitation ;)

I will stop here, you dont want the features i offered, i respect this even if you has not ask the comunity if they want this. So have fun, see you ingame maybe ....

**Comment by thekroko** [comment]
Scraping of data is not something you should aim for;  if you want a
feature, add it to the Uthgard herald instead (it's an open source
project!).

That being said, I didn't add or change anything related to rate limiting.
You might be saturating the configured global connection limits of the load
balancer, or of the backend db connections. Maybe you are also being
throttled on your side.

But again -- why not just implement the same feature set in the herald?
That way there is one unified source of truth that can be easily maintained.

**Comment by gilly42** [comment]
maybe its the load balancer .....

i tried to explain this in the other issues. i like features which show the progress of xp/rp, like
![rp_over_time](https://cloud.githubusercontent.com/assets/7795909/18551713/f4500d82-7b59-11e6-9ec6-a394f5a396b9.png)
This is only possible if the data is saved over the time, not possible with your api. this is an backend feature. 

or data like this
![rp_over_realm](https://cloud.githubusercontent.com/assets/7795909/18551890/af6f9d94-7b5a-11e6-8fba-a7a2ce4f7f98.png)
for this i need all rps of all guilds the api has no such data, so i would need to get all data and add them manually

**Comment by thekroko** [comment]
I'd propose instead adding an official, open source frontend & backend combo that is hosted in this repository instead of having the herald spread throughout the web
